hmLoadTopic({
hmKeywords:"demon possessed daughter",
hmTitle:"An Odd Woman",
hmDescription:"Maybe Jesus was in a Jewish neighborhood, maybe he wasn\'t, but he was in a Jewish home. And it takes a certain kind of brazenness for a Gentile woman to enter the home of...",
hmPrevLink:"02-the_canaanite.html",
hmNextLink:"02b-commentaries.html",
hmParentLink:"01-introduction.html",
hmBreadCrumbs:"<a href=\"01-introduction.html\">Introduction<\/a>",
hmTitlePath:"Introduction > An Odd Woman",
hmHeader:"<p class=\"p_heading_2_atoc_\"><span class=\"f_heading_2_atoc_\">An Odd Woman<\/span><\/p>\n\r",
hmBody:"<p class=\"p_body\"><span class=\"f_body\">Maybe Jesus was in a Jewish neighborhood, maybe he wasn\'t, but he was in a Jewish home. And it takes a certain kind of brazenness for a Gentile woman to enter the home of Jewish man. I mean this wasn\'t done. It violated cultural norms. First, Jews did not deal with Gentiles. Second, in those days, the man was the priest of his home. Third, the near-Eastern traditions of hospitality were sacred. Put all these factors together and it would have been extraordinarily unusual for a Jewish man to let a Canaanite woman into his house and let her touch Jesus in any way. My feeling is that she burst into the home and clutched Jesus\'s feet in desperation.<\/span><\/p>\n\r<p class=\"p_body\"><span class=\"f_body\">The Syro-Phoenician woman was odd. She was a Gentile living in a world where non-Jewish religion was the norm, but she chose to worship the Israel\'s God. She evidently was connected to the Jewish community in some way, a people who would have despised her ancestry, and whom the people in culture probably didn\'t like or didn\'t trust. She also had a stubborn independence that was unusually manifest in for women who from childhood were taught to be submissive, quiet and obedient. <\/span><\/p>\n\r<p class=\"p_body\"><span class=\"f_body\">Now this woman has a problem. It\'s funny how odd people often how odd problems. Her daughter was demon possessed. Her daughter wasn’t merely sick; she had a demon. In BWCC we don’t get too many prayer requests like that: <\/span><span class=\"f_quote\">“pray for my son, he has a demon.”<\/span><span class=\"f_body\"> But what is also interesting, that when odd people, have odd problems and they desperately need a problems, they don\'t mess around with protocol. This woman threw herself at the feet of Jesus and asks Jesus to cast the demon out of her daughter. Jesus’s reply is: <\/span><\/p>\n\r<p class=\"p_scripture\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture\">“Let the children be fed first, for it is not right to take the children\'s bread and throw it to the dogs.” <\/span><\/p>\n\r"
})
