hmLoadTopic({
hmKeywords:"",
hmTitle:"A Single Desire",
hmDescription:"This is a simple concept, but great faith is focused on receiving a single thing. The Syro-Phoenician woman knew what she wanted. ",
hmPrevLink:"06-application_today.html",
hmNextLink:"06b-focus_on_god_not_self.html",
hmParentLink:"01-introduction.html",
hmBreadCrumbs:"<a href=\"01-introduction.html\">Introduction<\/a>",
hmTitlePath:"Introduction > A Single Desire",
hmHeader:"<p class=\"p_heading_2_atoc_\"><span class=\"f_heading_2_atoc_\">A Single Desire<\/span><\/p>\n\r",
hmBody:"<p class=\"p_body\"><span class=\"f_body\">This is a simple concept, but great faith is focused on receiving a single thing. The Syro-Phoenician woman knew what she wanted. <\/span><\/p>\n\r<p class=\"p_body\"><span class=\"f_body\">Sometimes in our prayer meetings, people will say,<\/span><span class=\"f_quote\"> “Pray for my neighbor, he or she is sick.”<\/span><span class=\"f_body\"> However, many times these requests come across as top of the head. You have to realize there is a difference between prayer and faith. We can pray in unbelief. Our goal is to pray in faith. To pray in faith we have to be specific. And to be specific we have to provide details and understand what is going enough so that you can properly discern what the need is.<\/span><\/p>\n\r<p class=\"p_body\"><span class=\"f_body\">I\'ll use myself as an example because I don\'t want you to think I\'m picking on you. If a friend or loved one is sick, usually I have to talk to that person and find out what is going, try to locate spiritually so that I can pray effectively. Often I pray for Christians differently than non-Christians. I pray for people I know well that are struggling with specific sins that have contributed to their sicknesses differently than someone who is going through an attack from the enemy. This includes myself. <\/span><\/p>\n\r<p class=\"p_body\"><span class=\"f_body\">Here\'s the point, if you want God to answer your prayer, you have to believe that in your heart that is he going to do what you ask. The issue isn\'t whether God can or if God is willing, as much as whether we are being specific in our praying. &nbsp;I can say, <\/span><span class=\"f_quote\">&quot;Let\'s pray for all the hungry people in the world&quot;<\/span><span class=\"f_body\">, but that is a toothless prayer because it is so vague and general. <\/span><\/p>\n\r<p class=\"p_body\"><span class=\"f_body\">I can start praying for the food pantries near where I live. I can start visiting them and talking to the volunteers that work there and find out what they need and start praying for the volunteers by need and pray for their specific needs. <\/span><\/p>\n\r"
})
