hmLoadTopic({
hmKeywords:"The Outsider",
hmTitle:"Message Information",
hmDescription:"Title: The Outsider Author: Reverend Paul Cooper Message Summary: This Gentile woman was the ultimate outsider in ancient Hebrew culture. But Jesus saw beyond her status to mee",
hmPrevLink:"",
hmNextLink:"01-introduction.html",
hmParentLink:"index.html",
hmBreadCrumbs:"",
hmTitlePath:"Message Information",
hmHeader:"<p class=\"p_heading_1_atoc_\"><span class=\"f_heading_1_atoc_\">Message Information<\/span><\/p>\n\r",
hmBody:"<p class=\"p_Normal\" style=\"text-align: center;\">&nbsp;<\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 2.1250rem; margin-left: 1.2500rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:2.1250rem;margin-left:-2.1250rem\">&#8226;<\/span><span class=\"f_bullet\" style=\"font-weight: bold;\">Title:<\/span><span class=\"f_bullet\"> The Outsider<\/span><\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 2.1250rem; margin-left: 1.2500rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:2.1250rem;margin-left:-2.1250rem\">&#8226;<\/span><span class=\"f_bullet\" style=\"font-weight: bold;\">Author:<\/span><span class=\"f_bullet\"> Reverend Paul Cooper<\/span><\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 2.1250rem; margin-left: 1.2500rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:2.1250rem;margin-left:-2.1250rem\">&#8226;<\/span><span class=\"f_bullet\" style=\"font-weight: bold;\">Message Summary: <\/span><span class=\"f_bullet\">This Gentile woman was the ultimate outsider in ancient Hebrew culture. But Jesus saw beyond her status to meet her need.<\/span><\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 2.1250rem; margin-left: 1.2500rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:2.1250rem;margin-left:-2.1250rem\">&#8226;<\/span><span class=\"f_bullet\"><a href=\"https:\/\/www.messagelink.in\/master_message_directory\/\$_master_directory\/scripture-copyright-info2.html\" target=\"_blank\" class=\"weblink\">Scripture copyright information<\/a><\/span><\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 2.1250rem; margin-left: 1.2500rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:2.1250rem;margin-left:-2.1250rem\">&#8226;<\/span><span class=\"f_bullet\"><a href=\"https:\/\/www.messagelink.in\/master_message_directory\/\$_master_directory\/index.html\" target=\"_blank\" class=\"weblink\">Message Directory<\/a><\/span><\/p>\n\r<p class=\"p_bullet\"><span class=\"f_bullet\">&nbsp;<\/span><\/p>\n\r"
})
