hmLoadTopic({
hmKeywords:"",
hmTitle:"Conclusion",
hmDescription:"I conclude this message with a few closing thoughts.",
hmPrevLink:"jesusafulfillmentofscripture.html",
hmNextLink:"scriptureindexforheisrisen.html",
hmParentLink:"introduction.html",
hmBreadCrumbs:"<a href=\"introduction.html\">Introduction<\/a>",
hmTitlePath:"Introduction > Conclusion",
hmHeader:"<p class=\"p_heading1\"><span class=\"f_heading1\">Conclusion<\/span><\/p>\n\r",
hmBody:"<p class=\"p_body\"><span class=\"f_body\">I conclude this message with a few closing thoughts.<\/span><\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 1.5000rem; margin: 0.3750rem 0 0.5000rem 1.8750rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">&#8226;<\/span><span class=\"f_bullet\">The greater the triumph the greater the persecution. The Apostles were the first to share the glorious truth of Christ’s resurrection to the world. As a result, they faced searing persecution for their witness. You and I should not think our faithful witness will produce different results.<\/span><\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 2.1250rem; margin-left: 1.2500rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">&#8226;<\/span><span class=\"f_bullet\">This triumphant message of Jesus Christ must seep into our spiritual bones as it were, and we must not let the enemy steal it from our hearts. We can’t waste time arguing with people about whether the tomb is empty or whether Jesus was born of a virgin. <\/span><span class=\"f_emphasis\">Are you kidding me?<\/span><span class=\"f_bullet\"> We must get busy working with Christ, but before we do anything else, we need filled with God’s Holy Spirit. <\/span><\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 2.1250rem; margin-left: 1.2500rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">&#8226;<\/span><span class=\"f_bullet\">Finally, we are going to have to individually be stronger in God. I pray this is not a sermon that you forget. I pray that this message will inspire you reflect and ask yourself, <\/span><span class=\"f_emphasis\">“Given all that Christ has done for me, and is doing for me now, am I need where I need to be in Christ?”<\/span><\/p>\n\r<p class=\"p_body\"><span class=\"f_body\">Let us pray.<\/span><\/p>\n\r<p class=\"p_close\"><span class=\"f_close\">In the name of God, Amen<\/span><\/p>\n\r<p class=\"p_body\"><span class=\"f_body\">&nbsp;<\/span><\/p>\n\r"
})
