hmLoadTopic({
hmKeywords:"",
hmTitle:"Risen According to the Scriptures",
hmDescription:"The resurrection of Jesus of Nazareth is one of the most important events ever recorded—period. There are three connectors to this concept in the Scriptures that we read:",
hmPrevLink:"thefactoftheresurrection.html",
hmNextLink:"theinfinitegodbecomes%C2%A0man.html",
hmParentLink:"introduction.html",
hmBreadCrumbs:"<a href=\"introduction.html\">Introduction<\/a>",
hmTitlePath:"Introduction > Risen According to the Scriptures",
hmHeader:"<p class=\"p_heading1\"><span class=\"f_heading1\">Risen According to the Scriptures<\/span><\/p>\n\r",
hmBody:"<p class=\"p_body\"><span class=\"f_body\">The resurrection of Jesus of Nazareth is one of the most important events ever recorded—period. There are three connectors to this concept in the Scriptures that we read:<\/span><\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 1.5000rem; margin: 0.3750rem 0 0.5000rem 1.8750rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">&#8226;<\/span><span class=\"f_bullet\">Connector 1: The Apostles all emphasize the Jesus died, was buried, and was raised <\/span><span class=\"f_emphasis\">in accordance with the Scriptures.<\/span><span class=\"f_bullet\"> The resurrection, like everything significant in the life of Jesus, was a fulfillment of Scripture.<\/span><\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 1.5000rem; margin: 0.3750rem 0 0.5000rem 1.8750rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">&#8226;<\/span><span class=\"f_bullet\">Connector 2: The death, burial and resurrection of Jesus<\/span><span class=\"f_emphasis\"> is the foundational message<\/span><span class=\"f_bullet\"> that Jesus taught his disciples and Paul after he was raised from the dead.<\/span><\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 1.5000rem; margin: 0.3750rem 0 0.5000rem 1.8750rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">&#8226;<\/span><span class=\"f_bullet\">Connector 3: The death, burial and resurrection of Jesus as supported by Old Testament scripture<\/span><span class=\"f_emphasis\"> is the main argument<\/span><span class=\"f_emphasis\" style=\"font-size: 1.27rem;\"> <\/span><span class=\"f_bullet\">of the Peter’s sermon on Pentecost, and the consistent message of Peter, Paul, Barnabas, and Silas in the book of Acts.<\/span><\/p>\n\r<p class=\"p_body\"><span class=\"f_body\">&nbsp;<\/span><\/p>\n\r"
})
