hmLoadTopic({
hmKeywords:"",
hmTitle:"The Burial of Jesus",
hmDescription:"Why is that important? Burial represents finality. If you have ever been to a funeral, you know that there is a certain finality when the coffin is lowered into the ground,...",
hmPrevLink:"thespirit%C2%A0man.html",
hmNextLink:"themustoftheresurrection.html",
hmParentLink:"thedeath%C2%A0of%C2%A0jesus.html",
hmBreadCrumbs:"<a href=\"introduction.html\">Introduction<\/a> &gt; <a href=\"thedeath%C2%A0of%C2%A0jesus.html\">The Death&nbsp;of&nbsp;Jesus<\/a>",
hmTitlePath:"Introduction > The Death of Jesus > The Burial of Jesus",
hmHeader:"<p class=\"p_heading_2_atoc_\"><span class=\"f_heading_2_atoc_\">The Burial of Jesus<\/span><\/p>\n\r",
hmBody:"<p class=\"p_body\"><span class=\"f_body\">Why is that important? Burial represents finality. If you have ever been to a funeral, you know that there is a certain finality when the coffin is lowered into the ground, right? If the person’s passing doesn’t seem real up to that point, often it gets real as the coffin is placed in the ground. Jesus\'s burial emphasized that he was stone cold dead! &nbsp;However, he also had to rise on the 3rd day to fulfill the Scriptures.<\/span><\/p>\n\r<p class=\"p_heading3\" style=\"page-break-inside: avoid; page-break-after: avoid; margin: 0.5000rem 0 1.0000rem 0.1875rem;\"><span class=\"f_heading3\">The Spirit of Christ in Hades<\/span><\/p>\n\r<p class=\"p_body\"><span class=\"f_body\">Well, you might say, <\/span><span class=\"f_quote\">yes , Jesus body was expired and, in a tomb, but his spirit lived on. Well, where was his spirit? Where was God the Son now that spirit of God the Son had been released from the body of Jesus?<\/span><\/p>\n\r<p class=\"p_body\"><span class=\"f_body\">The spirit of Jesus went to Paradise. That’s where the second thief on the cross was, that is where Abraham, David and all the other men and women of faith. This is probably what Ephesians 4 is talking about when is says that Jesus first descended before he ascended:<\/span><\/p>\n\r<p class=\"p_scripture_head\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture_head\">Ephesians 4:8-10 English Standard Version<\/span><\/p>\n\r<p class=\"p_scripture\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture\">8 Therefore it says,<\/span><\/p>\n\r<p class=\"p_scripture\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture\">“When he ascended on high he led a host of captives,<\/span><\/p>\n\r<p class=\"p_scripture\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture\"> &nbsp; &nbsp;and he gave gifts to men.”<\/span><\/p>\n\r<p class=\"p_scripture\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture\">9 (In saying, “He ascended,” what does it mean <\/span><span class=\"f_scripture\" style=\"background-color: #ffff00;\">but that he had also descended into the lower regions<\/span><span class=\"f_scripture\">, the earth?<\/span><br \/>\n\r<span class=\"f_scripture\">10 He who descended is the one who also ascended far above all the heavens, that he might fill all things.)<\/span><\/p>\n\r"
})
