hmLoadTopic({
hmKeywords:"",
hmTitle:"The Must of the Resurrection",
hmDescription:"Now this brings us to the resurrection. Jesus of Nazareth is dead. God the Son isn’t dead, but the body of Jesus is a corpse lying on a marble slab.",
hmPrevLink:"theburial%C2%A0of%C2%A0jesus.html",
hmNextLink:"thefactoftheresurrection.html",
hmParentLink:"thedeath%C2%A0of%C2%A0jesus.html",
hmBreadCrumbs:"<a href=\"introduction.html\">Introduction<\/a> &gt; <a href=\"thedeath%C2%A0of%C2%A0jesus.html\">The Death&nbsp;of&nbsp;Jesus<\/a>",
hmTitlePath:"Introduction > The Death of Jesus > The Must of the Resurrection",
hmHeader:"<p class=\"p_heading_2_atoc_\"><span class=\"f_heading_2_atoc_\">The Must of the Resurrection<\/span><\/p>\n\r",
hmBody:"<p class=\"p_body\"><span class=\"f_body\">Now this brings us to the resurrection. Jesus of Nazareth is dead. God the Son isn’t dead, but the body of Jesus is a corpse lying on a marble slab.<\/span><\/p>\n\r<p class=\"p_body\"><span class=\"f_body\">Although Jesus’s spirit is alive, we still refer to Jesus as dying because, well, Jesus is the unique amalgamation of God and man. Without God the Son, a sinless Jesus can’t exist. And without the human body born of Mary, a bodiless Jesus can’t exist. A Jesus without the body of Mary’s son is no Jesus at all.<\/span><\/p>\n\r<p class=\"p_body\"><span class=\"f_emphasis\">The body of Jesus of Nazareth is as unique as a thumbprint.<\/span><span class=\"f_body\"> It’s not just that God the Son could be born to just any virgin. God had to be born to that specific virgin who was betrothed to that specific man, whose aunt was that specific woman, whose husband was that specific priest, and Jesus’s parents had to live in a specific place and participate in a specific census to be visited by specific wise men…you get the idea.<\/span><\/p>\n\r<p class=\"p_body\"><span class=\"f_body\">What I am saying is that this human part of Jesus is lying on a marble slab in a rich man’s tomb. If the spirit of God the Son is not rejoined to that specific body, and resurrected back to life, not only would God’s plan of redemption be an utter failure, but God Himself would be found out to be a lie, BECAUSE God would be unable to fulfill the Scripture of raising Jesus of Nazareth from the dead and not leaving his spirit in Hades. And if one Bible promise cannot be kept, then all of them are broken, and the whole Bible is a lie. Since God and his Word are One, God is found out to be a lie and we are all in big trouble.<\/span><\/p>\n\r<p class=\"p_body\"><span class=\"f_body\">Now if God can do all things, <\/span><span class=\"f_emphasis\">what is the only thing that might have prevented the resurrection of Jesus?<\/span><span class=\"f_emphasis\" style=\"font-size: 1.27rem;\"> <\/span><span class=\"f_body\">The only thing that could have prevented the resurrection of Jesus is if Jesus were not sinless and blameless and God the Father somehow found his offering for man’s sin to be wanting. Therefore, the resurrection of Christ validates that Jesus was without sin and that the Father accepted of Jesus\'s sacrifice on the cross.<\/span><\/p>\n\r"
})
