hmLoadTopic({
hmKeywords:"",
hmTitle:"Conclusion",
hmDescription:"In conclusion, we have established: that sin is willful disobedience to the Law of God. Because of our sins, we are condemned as guilty before a holy God. Jesus bore our sins in",
hmPrevLink:"theslatewiped%C2%A0clean.html",
hmNextLink:"scriptureindexforthecontraryslatewipedclean.html",
hmParentLink:"index.html",
hmBreadCrumbs:"",
hmTitlePath:"Conclusion",
hmHeader:"<p class=\"p_heading_1_atoc_\"><span class=\"f_heading_1_atoc_\">Conclusion<\/span><\/p>\n\r",
hmBody:"<p class=\"p_body\"><span class=\"f_body\">In conclusion, we have established:<\/span><\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 2.1250rem; margin-left: 1.2500rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:2.1250rem;margin-left:-2.1250rem\">&#8226;<\/span><span class=\"f_bullet\">that sin is willful disobedience to the Law of God. Because of our sins, we are condemned as guilty before a holy God.<\/span><\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 2.1250rem; margin-left: 1.2500rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:2.1250rem;margin-left:-2.1250rem\">&#8226;<\/span><span class=\"f_bullet\">Jesus bore our sins in his body on the cross<\/span><span class=\"f_bullet\" style=\"font-family: \'Times New Roman\',Times,Georgia,serif;\">.<\/span><span class=\"f_bullet\"> His body became the record of charges of our guilt. God punished Jesus of Nazareth for our sins instead of us. By suffering and dying on the cross, Jesus paid in full the debt incurred by our sins and satisfied God’s righteous judgment.<\/span><\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 2.1250rem; margin-left: 1.2500rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:2.1250rem;margin-left:-2.1250rem\">&#8226;<\/span><span class=\"f_bullet\">God raised Jesus from the dead, proving that Jesus is God and had never sinned.<\/span><\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 2.1250rem; margin-left: 1.2500rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:2.1250rem;margin-left:-2.1250rem\">&#8226;<\/span><span class=\"f_bullet\">God’s triumph in the resurrection of Jesus becomes the triumph for those of us who have placed our faith in Christ. Our sin debt is paid, and there is no longer a record of charges against us.<\/span><\/p>\n\r<p class=\"p_body\"><span class=\"f_body\">Our understanding of biblical concepts of justification and righteousness is the difference between a victorious Christian life and a defeated Christian life<\/span><span class=\"f_body\" style=\"font-family: \'Times New Roman\',Times,Georgia,serif;\">.<\/span><span class=\"f_body\"> We must give ourselves to deeply understanding God’s plan of redemption. This will build our faith and transform our relationship with God, our relationship with one another in Christ, and our image of ourselves. May the Holy Spirit continue to guide us into all truth on these issues.<\/span><\/p>\n\r<p class=\"p_body\"><span class=\"f_close\">In the name of God, Amen.<\/span><\/p>\n\r"
})
