hmLoadTopic({
hmKeywords:"",
hmTitle:"Message Information",
hmDescription:"Title: Crucified with Christ Author: Pastor Paul Cooper Message Summary: A look at the meaning of the crucifixion of Jesus of Nazareth Scripture copyright information Message",
hmPrevLink:"",
hmNextLink:"hlk101608883.html#jean",
hmParentLink:"index.html",
hmBreadCrumbs:"",
hmTitlePath:"Message Information",
hmHeader:"<p class=\"p_heading_1_atoc_\"><span class=\"f_heading_1_atoc_\">Message Information<\/span><\/p>\n\r",
hmBody:"<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 1.5000rem; margin-left: 2.0000rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">&#8226;<\/span><span class=\"f_bullet\" style=\"font-weight: bold;\">Title:<\/span><span class=\"f_bullet\"> Crucified with Christ<\/span><\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 1.5000rem; margin-left: 2.0000rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">&#8226;<\/span><span class=\"f_bullet\" style=\"font-weight: bold;\">Author:<\/span><span class=\"f_bullet\"> Pastor Paul Cooper<\/span><\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 1.5000rem; margin-left: 2.0000rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">&#8226;<\/span><span class=\"f_bullet\" style=\"font-weight: bold;\">Message Summary: <\/span><span class=\"f_bullet\">A look at the meaning of the crucifixion of Jesus of Nazareth<\/span><\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 1.5000rem; margin-left: 2.0000rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">&#8226;<\/span><span class=\"f_bullet\"><a href=\"https:\/\/s3.amazonaws.com\/b-wcc.org\/scripturecopyright.htm\" target=\"_blank\" class=\"weblink\">Scripture copyright information<\/a><\/span><\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 1.5000rem; margin-left: 2.0000rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">&#8226;<\/span><span class=\"f_bullet\"><a href=\"www.messagelink.com\/_htmloutput\/mastermessagedirectory.html\" target=\"_blank\" class=\"weblink\">Message Directory<\/a><\/span><\/p>"
})
