hmLoadTopic({
hmKeywords:"",
hmTitle:"Message Information",
hmDescription:"Title: He is Not Here Author: Pastor Paul Cooper Message Summary: Jesus is no longer in the tomb; Christ is risen! Scripture copyright information Message Directory",
hmPrevLink:"",
hmNextLink:"scripture-list.html",
hmParentLink:"index.html",
hmBreadCrumbs:"",
hmTitlePath:"Message Information",
hmHeader:"<p>Message Information<\/p>\n\r",
hmBody:"<p style=\"text-indent: 0; padding-left: 1.5000rem; margin: 0.3125rem 0 0.3125rem 2.0000rem;\"><span class=\"f_Normal\" style=\"font-size:1.20rem; font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">&#8226;<\/span><span style=\"font-size: 1.20rem; font-family: \'Open Sans\'; font-weight: bold;\">Title:<\/span><span style=\"font-size: 1.20rem; font-family: \'Open Sans\';\"> He is Not Here<\/span><\/p>\n\r<p style=\"text-indent: 0; padding-left: 1.5000rem; margin: 0.3125rem 0 0.3125rem 2.0000rem;\"><span class=\"f_Normal\" style=\"font-size:1.20rem; font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">&#8226;<\/span><span style=\"font-size: 1.20rem; font-family: \'Open Sans\'; font-weight: bold;\">Author:<\/span><span style=\"font-size: 1.20rem; font-family: \'Open Sans\';\"> Pastor Paul Cooper<\/span><\/p>\n\r<p style=\"text-indent: 0; padding-left: 1.5000rem; margin: 0.3125rem 0 0.3125rem 2.0000rem;\"><span class=\"f_Normal\" style=\"font-size:1.20rem; font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">&#8226;<\/span><span style=\"font-size: 1.20rem; font-family: \'Open Sans\'; font-weight: bold;\">Message Summary: <\/span><span style=\"font-size: 1.20rem; font-family: \'Open Sans\';\">Jesus is no longer in the tomb; Christ is risen!<\/span><\/p>\n\r<p style=\"text-indent: 0; padding-left: 1.5000rem; margin: 0.3125rem 0 0.3125rem 2.0000rem;\"><span class=\"f_Normal\" style=\"font-size:1.20rem; font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">&#8226;<\/span><span style=\"font-size: 1.20rem; font-family: \'Open Sans\';\"><a href=\"https:\/\/s3.amazonaws.com\/b-wcc.org\/scripturecopyright.htm\" target=\"_blank\" class=\"weblink\">Scripture copyright information<\/a><\/span><\/p>\n\r<p style=\"text-indent: 0; padding-left: 1.5000rem; margin: 0.3125rem 0 0.3125rem 2.0000rem;\"><span class=\"f_Normal\" style=\"font-size:1.20rem; font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">&#8226;<\/span><span style=\"font-size: 1.20rem; font-family: \'Open Sans\';\"><a href=\"www.messagelink.com\/_htmloutput\/mastermessagedirectory.html\" target=\"_blank\" class=\"weblink\">Message Directory<\/a><\/span><\/p>"
})
