hmLoadTopic({
hmKeywords:"resurrection,validation",
hmTitle:"The Biblical Meaning of Resurrection",
hmDescription:"The word “resurrection” means to be brought back to life. All men have a desire to live physically and spiritually. This is because God created man to live forevernot just...",
hmPrevLink:"introduction.html",
hmNextLink:"themeaningtothechurch.html",
hmParentLink:"themeaningoftheresurrection.html",
hmBreadCrumbs:"<a href=\"themeaningoftheresurrection.html\">The Meaning of the Resurrection<\/a>",
hmTitlePath:"The Meaning of the Resurrection > The Biblical Meaning of Resurrection",
hmHeader:"<p class=\"p_heading1\"><span class=\"f_heading1\">The Biblical Meaning of Resurrection<\/span><\/p>\n\r",
hmBody:"<p class=\"p_body\"><span class=\"f_body\">The word “resurrection” means to be brought back to life. All men have a desire to live physically and spiritually. This is because God created man to live forevernot just exist, &nbsp;amoebas and frogs exist, but to have in eternal fellowship with God. Through sin, death entered the world, and man died spiritually and physically.<\/span><\/p>\n\r<p class=\"p_body\"><span class=\"f_body\">Since the fall of man, people have clung to the hope of a resurrection. Since God is the giver of life, people understood that God would not only initiate the resurrection but that the resurrection would involve a judgment over which God, the just judge, would preside. Therefore, biblically, the concept of resurrection and judgment go together. Judgment, of course, validation or approval. When God judges the resurrected, he will express his approval or disapproval regarding the life they lived and what they believed. We see this scenario played out in the Gospel of Matthew:<\/span><\/p>\n\r<p class=\"p_scripture_head\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture_head\">Matthew 25:31-33 New King James Version (NKJV)<\/span><\/p>\n\r<p class=\"p_scripture\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture\">31 “When the Son of Man comes in His glory, and all the holy angels with Him, then He will sit on the throne of His glory. 32 All the nations will be gathered before Him, and He will separate them one from another, as a shepherd divides his sheep from the goats. 33 And He will set the sheep on His right hand, but the goats on the left.<\/span><\/p>\n\r<p class=\"p_heading3\"><span class=\"f_heading3\">Resurrection as Validation<\/span><\/p>\n\r<p class=\"p_body\"><span class=\"f_body\">The Apostles Peter and Paul uniquely applied the &nbsp;to God raising Jesus from the dead. By raising Jesus and exalting him to sit at his right hand, God validated everything about &nbsp;truth claims.<\/span><\/p>\n\r"
})
