hmLoadTopic({
hmKeywords:"",
hmTitle:"简介",
hmDescription:"简介 罗马书10:1-4 英语标准版（ESV） 10 弟兄们、我心里所愿、为他们向神祈求、就是叫他们得救。2 我为他们作见证，说他们热心于神，却不是照着知识。3因为他们不知道神的义，想要建立自己的义，就不顺从神的义。4 因为基督是律法的末了，叫一切相信的人得了义。 罗马书10:4 新生活译本（NLT） 4 因为基督已经成就了制定律法的目的。 因此，所",
hmPrevLink:"index.html",
hmNextLink:"the-law-in-a-nutshell.html",
hmParentLink:"index.html",
hmBreadCrumbs:"<a href=\"index.html\">留言信息<\/a>",
hmTitlePath:"留言信息 > 简介",
hmHeader:"<p class=\"p_heading_1_atoc_\"><span class=\"f_heading_1_atoc_\">简介<\/span><\/p>\n\r",
hmBody:"<p style=\"text-indent: -3.0000rem; line-height: 1.28; page-break-inside: avoid; page-break-after: avoid; margin: 0.5000rem 0 0.5000rem 3.0000rem;\"><span style=\"font-size: 1.64rem; font-family: \'Franklin Gothic Book\'; font-weight: bold;\">简介<\/span><\/p>\n\r<p class=\"p_scripture_head\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture_head\">罗马书10:1-4 英语标准版（ESV）<\/span><\/p>\n\r<p class=\"p_scripture\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture\">10 弟兄们、我心里所愿、为他们向神祈求、就是叫他们得救。2 我为他们作见证，说他们热心于神，却不是照着知识。3因为他们不知道神的义，想要建立自己的义，就不顺从神的义。4 因为基督是律法的末了，叫一切相信的人得了义。<\/span><\/p>\n\r<p class=\"p_scripture_head\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture_head\">罗马书10:4 新生活译本（NLT）<\/span><\/p>\n\r<p class=\"p_scripture\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture\">4 因为基督已经成就了制定律法的目的。 因此，所有相信他的人都能在神面前称义。<\/span><\/p>\n\r<p class=\"p_scripture_head\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture_head\">罗马书 10:4 霍尔曼基督教标准圣经 (HCSB)<\/span><\/p>\n\r<p class=\"p_scripture\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture\">4 因为基督是律法的目的[或目标]，使凡相信的人得着公义。<\/span><\/p>\n\r<p class=\"p_scripture_head\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture_head\">罗马书 10:4 易读本 (ERV)<\/span><\/p>\n\r<p class=\"p_scripture\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture\">4 基督结束了律法，使每一个信他的人都能与神和好。<\/span><\/p>\n\r<p class=\"p_scripture_head\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture_head\">罗马书 10:4 当代英语版本 (CEV)<\/span><\/p>\n\r<p class=\"p_scripture\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture\">4 但基督使那些因信成为神所喜悦的人不再需要律法。<\/span><\/p>\n\r<p class=\"p_scripture_head\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture_head\">罗马书10:4扩展版圣经（EXB）<\/span><\/p>\n\r<p class=\"p_scripture\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture\">4 [L For] Christ -ended [is the end\/culmination\/fulfillment of] the law so that everyone who believe in him may - be right with God [have righteousness].<\/span><\/p>\n\r<p class=\"p_body\"><span class=\"f_body\">了解我们与律法的关系对于与主建立健康的关系至关重要。困扰早期教会的最突出的异端之一--律法主义--是基于对摩西律法在信徒生活中的作用的歪曲理解。犹太主义者坚持认为所有的基督徒都要遵守摩西的律法才能得救，而使徒保罗则大力反对这种危险而有害的教义。<\/span><\/p>\n\r<p class=\"p_body\"><span class=\"f_body\">新约中还提到了其他异端邪说，但这种错误的教导在大多数使徒的著作中都被提及。因此，我们需要正确理解一般的旧约，特别是律法，以免我们落入这种阴险的教导。<\/span><\/p>\n\r<p style=\"line-height: 1.28; margin: 0 0 0.5000rem 0;\"><span style=\"font-size: 0.91rem; font-family: Arial,Helvetica,sans-serif; color: #000000;\">&nbsp;<\/span><\/p>\n\r"
})
