hmLoadTopic({
hmKeywords:"",
hmTitle:"Message Information",
hmDescription:"Title: David in Winter Author: Pastor Paul Cooper Message Summary: A look at how God transitions his people from one season to the next. Scripture copyright information Messa",
hmPrevLink:"",
hmNextLink:"introduction.html",
hmParentLink:"index.html",
hmBreadCrumbs:"",
hmTitlePath:"Message Information",
hmHeader:"<p class=\"p_heading_1_atoc_\"><span class=\"f_heading_1_atoc_\">Message Information<\/span><\/p>\n\r",
hmBody:"<p class=\"p_Normal\"><a href=\"http:\/\/www.b-wcc.org\" target=\"_blank\"><img alt=\"2_small_logo_no_words\" style=\"margin:0;width:8.7500rem;height:8.1875rem;border:none\" src=\".\/images\/2_small_logo_no_words.png\"\/><\/a><\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 1.5000rem; margin-left: 2.0000rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">&#8226;<\/span><span class=\"f_bullet\" style=\"font-weight: bold;\">Title:<\/span><span class=\"f_bullet\"> David in Winter<\/span><\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 1.5000rem; margin-left: 2.0000rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">&#8226;<\/span><span class=\"f_bullet\" style=\"font-weight: bold;\">Author:<\/span><span class=\"f_bullet\"> Pastor Paul Cooper<\/span><\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 1.5000rem; margin-left: 2.0000rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">&#8226;<\/span><span class=\"f_bullet\" style=\"font-weight: bold;\">Message Summary: <\/span><span class=\"f_bullet\">A look at how God transitions his people from one season to the next.<\/span><\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 1.5000rem; margin-left: 2.0000rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">&#8226;<\/span><span class=\"f_bullet\"><a href=\"https:\/\/s3.amazonaws.com\/b-wcc.org\/scripturecopyright.htm\" target=\"_blank\" class=\"weblink\">Scripture copyright information<\/a><\/span><\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 1.5000rem; margin-left: 2.0000rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">&#8226;<\/span><span class=\"f_bullet\"><a href=\"www.messagelink.com\/_htmloutput\/mastermessagedirectory.html\" target=\"_blank\" class=\"weblink\">Message Directory<\/a><\/span><\/p>"
})
