hmLoadTopic({
hmKeywords:"",
hmTitle:"Message Information",
hmDescription:"Title: The Apparent Contradiction of the Christ Author: Pastor Paul Cooper Message Summary: The conquered nation of Israel eagerly anticipated a warrior messiah, instead God ga",
hmPrevLink:"",
hmNextLink:"introduction.html",
hmParentLink:"index.html",
hmBreadCrumbs:"",
hmTitlePath:"Message Information",
hmHeader:"<p class=\"p_heading_1_atoc_\"><span class=\"f_heading_1_atoc_\">Message Information<\/span><\/p>\n\r",
hmBody:"<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 2.1250rem; margin-left: 1.2500rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:2.1250rem;margin-left:-2.1250rem\">&#8226;<\/span><span class=\"f_bullet\" style=\"font-weight: bold;\">Title:<\/span><span class=\"f_bullet\"> The Apparent Contradiction of the Christ<\/span><\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 2.1250rem; margin-left: 1.2500rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:2.1250rem;margin-left:-2.1250rem\">&#8226;<\/span><span class=\"f_bullet\" style=\"font-weight: bold;\">Author:<\/span><span class=\"f_bullet\"> Pastor Paul Cooper<\/span><\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 2.1250rem; margin-left: 1.2500rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:2.1250rem;margin-left:-2.1250rem\">&#8226;<\/span><span class=\"f_bullet\" style=\"font-weight: bold;\">Message Summary: <\/span><span class=\"f_bullet\">The conquered nation of Israel eagerly anticipated a warrior messiah, instead God gave them a king who came to die for their sins.<\/span><\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 2.1250rem; margin-left: 1.2500rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:2.1250rem;margin-left:-2.1250rem\">&#8226;<\/span><span class=\"f_bullet\"><a href=\"https:\/\/messagelink.in\/master_message_directory\/\$_master_directory\/scripture-copyright-info2.html\" target=\"_blank\" class=\"weblink\">Scripture copyright information<\/a><\/span><\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 2.1250rem; margin-left: 1.2500rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:2.1250rem;margin-left:-2.1250rem\">&#8226;<\/span><span class=\"f_bullet\"><a href=\"https:\/\/messagelink.in\/master_message_directory\/\$_master_directory\/index.html\" target=\"_blank\" class=\"weblink\">Message Directory<\/a><\/span><\/p>"
})
