hmLoadTopic({
hmKeywords:"",
hmTitle:"Introduction",
hmDescription:"Let’s examine the world into which Jesus was born. The nation Israel was subject to the most powerful empire on earth at the time, the Roman Empire. Thirty years before Jesus...",
hmPrevLink:"index.html",
hmNextLink:"thepreferencesofisrael.html",
hmParentLink:"index.html",
hmBreadCrumbs:"",
hmTitlePath:"Introduction",
hmHeader:"<p class=\"p_heading_1_atoc_\"><span class=\"f_heading_1_atoc_\">Introduction<\/span><\/p>\n\r",
hmBody:"<p class=\"p_body\"><span class=\"f_body\">Let’s examine the world into which Jesus was born. The nation Israel was subject to the most powerful empire on earth at the time, the Roman Empire. Thirty years before Jesus was born, Rome had recently completed a bloody civil war. Gaius Octavius, grandnephew of the murdered Julius Caesar, was one of three generals who each ruled a third of Rome. Gaius successfully eliminated his rivals and consolidated his reign after conquering Egypt. The Roman Senate gave him the name Augustus Caesar, and he transformed Rome from a republic to an absolute monarchy.<\/span><\/p>\n\r<p class=\"p_heading_2_atoc_\"><span class=\"f_heading_2_atoc_\">The Power of Rome<\/span><\/p>\n\r<p class=\"p_body\"><span class=\"f_body\">Augustus Caesar proved to be brilliant administrator and used the plunder of his foreign conquests to revitalize the Roman economy, strengthen the military and bring overall stability to one of the greatest empires the world has known.<\/span><span style=\"font-size: 1.09rem;\"> <\/span><span class=\"f_body\">The governance of Augustus Caesar ushered in the<\/span><span class=\"f_emphasis\"> Pax Romana, <\/span><span class=\"f_body\">which was two hundred years of peace and prosperity for Rome. Jesus was born into the golden age of Rome.<\/span><\/p>\n\r<p class=\"p_body\"><span class=\"f_body\">However, the wealth of the Roman Empire did not extend to the people that Rome had conquered. Rome built its prosperity on the backs of slaves, the rape and pillage of sovereign nations, and the heavy taxation of subjugated peoples. These conquered people lived under the oppressive, humiliating shadow of an invincible military state. Israel was among the conquered of Rome.<\/span><\/p>\n\r<p class=\"p_body\"><span class=\"f_body\">Although Israel had the honor of being the only nation on earth created by God and uniquely his inheritance, they had fallen far from the heights of national sovereignty and blessing they had known under King David and King Solomon. Once a wealthy and respected nation feared by its enemies, Israel had endured centuries of plunder and domination by the Gentile nations they so despised. Israel\'s domination by a nation that had no respect for the God of Abraham was an unbearable national disgrace.<\/span><\/p>\n\r<p class=\"p_body\"><span class=\"f_emphasis\">Down to a person, the greatest longing of the Jewish people was the restoration of their national sovereignty and manifestation of God’s favor on the nation. <\/span><span class=\"f_body\">That yearning was embodied in the prophecies of a Savior\/​Messiah—a figure who would restore Israel spiritually, and most especially, nationally.<\/span><\/p>\n\r"
})
