hmLoadTopic({
hmKeywords:"",
hmTitle:"Simeon\'s prophecy",
hmDescription:"Luke 2:22-35 English Standard Version 22 And when the time came for their purification according to the Law of Moses, they brought him up to Jerusalem to present him to the...",
hmPrevLink:"scriptureindex.html",
hmNextLink:"zechariahsprophecy.html",
hmParentLink:"scriptureindex.html",
hmBreadCrumbs:"<a href=\"scriptureindex.html\">Scripture Index<\/a>",
hmTitlePath:"Scripture Index > Simeon\'s prophecy",
hmHeader:"<p class=\"p_heading_2_atoc_\"><span class=\"f_heading_2_atoc_\">Simeon\'s prophecy<\/span><\/p>\n\r",
hmBody:"<p class=\"p_scripture_head\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture_head\">Luke 2:22-35 English Standard Version<\/span><\/p>\n\r<p class=\"p_scripture\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture\">22 And when the time came for their purification according to the Law of Moses, they brought him up to Jerusalem to present him to the Lord 23 (as it is written in the Law of the Lord, “Every male who first opens the womb shall be called holy to the Lord”) 24 and to offer a sacrifice according to what is said in the Law of the Lord, “a pair of turtledoves, or two young pigeons.” 25 Now there was a man in Jerusalem, whose name was Simeon, and this man was righteous and devout, waiting for the consolation of Israel, and the Holy Spirit was upon him. 26 And it had been revealed to him by the Holy Spirit that he would not see death before he had seen the Lord\'s Christ. 27 And he came in the Spirit into the temple, and when the parents brought in the child Jesus, to do for him according to the custom of the Law, 28 he took him up in his arms and blessed God and said,<\/span><\/p>\n\r<p class=\"p_scripture\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture\">29 “Lord, now you are letting your servant depart in peace,<\/span><\/p>\n\r<p class=\"p_scripture\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture\"> &nbsp; &nbsp;according to your word;<\/span><\/p>\n\r<p class=\"p_scripture\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture\">30 for my eyes have seen your salvation<\/span><\/p>\n\r<p class=\"p_scripture\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture\">31 &nbsp; &nbsp; that you have prepared in the presence of all peoples,<\/span><\/p>\n\r<p class=\"p_scripture\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture\">32 a light for revelation to the Gentiles,<\/span><\/p>\n\r<p class=\"p_scripture\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture\"> &nbsp; &nbsp;and for glory to your people Israel.”<\/span><\/p>\n\r<p class=\"p_scripture\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture\">33 And his father and his mother marveled at what was said about him. 34 And Simeon blessed them and said to Mary his mother, “Behold, this child is appointed for the fall and rising of many in Israel, and for a sign that is opposed 35 (and a sword will pierce through your own soul also), so that thoughts from many hearts may be revealed.”<\/span><\/p>\n\r"
})
