hmLoadTopic({
hmKeywords:"",
hmTitle:"Zechariah\'s prophecy",
hmDescription:"Luke 1:67-75 English Standard Version 67 And his father Zechariah was filled with the Holy Spirit and prophesied, saying, 68 “Blessed be the Lord God of Israel,     for he has v",
hmPrevLink:"simeonsprophecy.html",
hmNextLink:"marys-prophecy.html",
hmParentLink:"scriptureindex.html",
hmBreadCrumbs:"<a href=\"scriptureindex.html\">Scripture Index<\/a>",
hmTitlePath:"Scripture Index > Zechariah\'s prophecy",
hmHeader:"<p class=\"p_heading_2_atoc_\"><span class=\"f_heading_2_atoc_\">Zechariah\'s prophecy<\/span><\/p>\n\r",
hmBody:"<p class=\"p_scripture_head\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture_head\">Luke 1:67-75 English Standard Version<\/span><\/p>\n\r<p class=\"p_scripture\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture\">67 And his father Zechariah was filled with the Holy Spirit and prophesied, saying,<\/span><\/p>\n\r<p class=\"p_scripture\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture\">68 “Blessed be the Lord God of Israel,<\/span><\/p>\n\r<p class=\"p_scripture\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture\"> &nbsp; &nbsp;for he has visited and redeemed his people<\/span><\/p>\n\r<p class=\"p_scripture\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture\">69 and has raised up a horn of salvation for us<\/span><\/p>\n\r<p class=\"p_scripture\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture\"> &nbsp; &nbsp;in the house of his servant David,<\/span><\/p>\n\r<p class=\"p_scripture\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture\">70 as he spoke by the mouth of his holy prophets from of old,<\/span><\/p>\n\r<p class=\"p_scripture\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture\">71 that we should be saved from our enemies<\/span><\/p>\n\r<p class=\"p_scripture\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture\"> &nbsp; &nbsp;and from the hand of all who hate us;<\/span><\/p>\n\r<p class=\"p_scripture\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture\">72 to show the mercy promised to our fathers<\/span><\/p>\n\r<p class=\"p_scripture\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture\"> &nbsp; &nbsp;and to remember his holy covenant,<\/span><\/p>\n\r<p class=\"p_scripture\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture\">73 the oath that he swore to our father Abraham, to grant us<\/span><\/p>\n\r<p class=\"p_scripture\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture\">74 &nbsp; &nbsp; that we, being delivered from the hand of our enemies,<\/span><\/p>\n\r<p class=\"p_scripture\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture\">might serve him without fear,<\/span><\/p>\n\r<p class=\"p_scripture\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture\">75 &nbsp; &nbsp; in holiness and righteousness before him all our days.<\/span><\/p>\n\r"
})
