hmLoadTopic({
hmKeywords:"",
hmTitle:"Conclusion",
hmDescription:"Let\'s review the principles we\'ve learned so far. God calls the church to live by faith, and describes living by faith also as fighting the good fight of faith.",
hmPrevLink:"toc49230363.html",
hmNextLink:"fightthegoodfightoffaith%C2%A0part%C2%A02.html",
hmParentLink:"fightthegoodfightoffaithpart%C2%A01.html",
hmBreadCrumbs:"<a href=\"fightthegoodfightoffaithpart%C2%A01.html\">Fight the Good Fight of Faith, Part&nbsp;1<\/a>",
hmTitlePath:"Fight the Good Fight of Faith, Part 1 > Conclusion",
hmHeader:"<p class=\"p_heading_1_atoc_\"><span class=\"f_heading_1_atoc_\">Conclusion<\/span><\/p>\n\r",
hmBody:"<p class=\"p_body\"><span class=\"f_body\">Let\'s review the principles we\'ve learned so far. God calls the church to live by faith, and describes living by faith also as <\/span><span class=\"f_emphasis\">fighting the good fight of faith.<\/span><\/p>\n\r<p class=\"p_body\"><span class=\"f_body\"> In Christ, God provides every believer with everything he or she needs to be victorious in this life. This life of spiritual victory and blessing is called various things in the Bible, including the blessing of Abraham, the promise, the inheritance, eternal life, or abundant life. (Of course, eternal life is <\/span><span class=\"f_emphasis\"> far<\/span><span class=\"f_body\"> more than material and temporal blessings, but it includes these things as well.) &nbsp;In order to receive our inheritance from God, or in order to receive a positive answer to prayer, we need to receive these blessings by faith. Receiving anything by faith almost always involves spiritual struggle and spiritual warfare.<\/span><\/p>\n\r<p class=\"p_body\"><span class=\"f_body\">Faith will not work if the believer asks for something contrary to the Word of God (the Word of God is the will of God). This is one of the reasons why God commanded Joshua to constantly meditate on the Word of God, so that Joshua\'s spirit and mind would be saturated with the Word and will of God. Therefore, the more Joshua was immersed in the Word of God, the more he understood what to trust God for, that is, <\/span><span class=\"f_emphasis\">what spiritual battles he should fight.<\/span><\/p>\n\r<p class=\"p_body\"><span class=\"f_body\">We also learn that we must also guard our hearts against the lusts of the flesh, such as greed, so that we will not be consumed by materialism and ungodly desires when we pray. God has called us to fight a good fight for our faith. Let us do so and win this battle for His glory.<\/span><\/p>\n\r<p class=\"p_Normal\"><span class=\"f_close\">In the name of God, Amen.<\/span><\/p>\n\r"
})
