hmLoadTopic({
hmKeywords:"",
hmTitle:"Our Struggles Come From Satan",
hmDescription:"The second failure is that we don’t see the relationship between our faith and ending our struggle. Many of us have been blinded to see that Jesus delivered people, which means...",
hmPrevLink:"authorityoveruncleanspirits.html",
hmNextLink:"fightthegoodoffaithappendixofscriptures.html",
hmParentLink:"fightthegoodfightoffaithpart.html",
hmBreadCrumbs:"<a href=\"fightthegoodfightoffaithpart.html\">Fight the Good Fight of Faith,&nbsp;Part&nbsp;4<\/a>",
hmTitlePath:"Fight the Good Fight of Faith, Part 4 > Our Struggles Come From Satan",
hmHeader:"<p class=\"p_heading_2_atoc_\"><span class=\"f_heading_2_atoc_\">Our Struggles Come From Satan<\/span><\/p>\n\r",
hmBody:"<p class=\"p_body\"><span class=\"f_body\">The second failure is that we don’t see the relationship between our faith and ending our struggle. Many of us have been blinded to see that Jesus delivered people, which means he ended their struggles. The boy with the powerful demon was delivered and that devil never came back. The widow’s son was raised up and went on to live a full life. The blind people Jesus healed went away seeing and died with 20\/​20 vision. Jesus attributed these permanent acts of power to faith.<\/span><\/p>\n\r<p class=\"p_heading_3_atoc_\"><span class=\"f_heading_3_atoc_\">An End to Specific Struggles<\/span><\/p>\n\r<p class=\"p_body\"><span class=\"f_body\">Many of us don’t realize that God wants to end our struggle. I didn’t say that we will never have ongoing problems in life. I am saying that the Lord wants to deliver us permanently from our <\/span><span class=\"f_emphasis\">present<\/span><span class=\"f_body\"> struggles so that we will have faith to overcome <\/span><span class=\"f_emphasis\">future<\/span><span class=\"f_body\"> struggles. But many of us quietly believe we will be sick with <\/span><span class=\"f_emphasis\">a particular sickness<\/span><span class=\"f_body\"> for the rest of our lives, that we will suffer a <\/span><span class=\"f_emphasis\">particular fate<\/span><span class=\"f_body\"> of loneliness or poverty for the rest of our lives. But the story of the demon-possessed son reminds us that God wants to end our struggles as they come, knocking them down like so many pins in a bowling lane!<\/span><\/p>\n\r<p class=\"p_heading_3_atoc_\"><span class=\"f_heading_3_atoc_\">The Faith Connection<\/span><\/p>\n\r<p class=\"p_body\"><span class=\"f_body\">The connection of course is faith. We need to have faith to overcome our struggles. Faith is trusting in God’s word not in secular methods. So, we must be very focused and clear on what the Bible teaches if we are to overcome our struggles by faith.<\/span><\/p>\n\r"
})
