hmLoadTopic({
hmKeywords:"Fight by training,Joshua 1:8 ",
hmTitle:"Get Full Of The Word",
hmDescription:"Every warrior must be prepared for battle. Soldiers invest substantial amounts of time in training. The equivalent for us is to spend immense amounts of time reading and...",
hmPrevLink:"beintherightfight.html",
hmNextLink:"conclusion.html",
hmParentLink:"fightthegoodfightoffaithpart%C2%A01.html",
hmBreadCrumbs:"<a href=\"fightthegoodfightoffaithpart%C2%A01.html\">Fight the Good Fight of Faith, Part&nbsp;1<\/a>",
hmTitlePath:"Fight the Good Fight of Faith, Part 1 > Get Full Of The Word",
hmHeader:"<p class=\"p_heading_1_atoc_\"><span class=\"f_heading_1_atoc_\">Get Full Of The Word<\/span><\/p>\n\r",
hmBody:"<p class=\"p_body\"><span class=\"f_body\">Every warrior must be prepared for battle. Soldiers invest substantial amounts of time in training. The equivalent for us is to spend immense amounts of time reading and meditating in Scripture. Expending this effort is a way that we fight the good fight of faith and lay hold of things that God has promised to us.<\/span><\/p>\n\r<p class=\"p_scripture_head\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture_head\">Joshua 1:8 English Standard Version (ESV)<\/span><\/p>\n\r<p class=\"p_scripture\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture\">8 This Book of the Law shall not depart from your mouth, but you shall meditate on it day and night, so that you may be careful to do according to all that is written in it. For then you will make your way prosperous, and then you will have good success.<\/span><\/p>\n\r<p class=\"p_body\"><span class=\"f_body\">The context of this verse is that God was commanding Joshua during his early conquest of the Promised Land. He and Israel were going to do battle with superhuman giants who practiced cannibalism and were engaged in all types of witchcraft and sorcery. These were some of the fiercest, most terrifying warriors ever. Remember, Israel was a nation of slaves not warriors who had no experience fighting superhuman giants. God was saying to Joshua that to win this battle, he had to speak the Word of God continually and constantly read and meditate on it. That was the only way Joshua was going to succeed.<\/span><\/p>\n\r<p class=\"p_heading_2_atoc_\"><span class=\"f_heading_2_atoc_\">Why Do We Fail?<\/span><\/p>\n\r<p class=\"p_body\"><span class=\"f_body\">We fail as Christians because we do not spend enough time meditating on the Word to build up our faith in specific areas. Instead, we are too quick to resort to trying to solve spiritual problems with natural solutions.<\/span><\/p>\n\r<p class=\"p_body\"><span class=\"f_body\">Let’s go back to Joshua. Israel was facing a mountain of a problem. They had to take land inhabited by demon-possessed giants that had supernatural strength. Notice Joshua didn’t say, “let’s start a rigorous training routine. Let’s take our gold and silver and buy chariots, swords, and shields.” Joshua sought the face of the Lord to get a supernatural answer to a supernatural problem. And God spoke to Joshua and commanded him to build up his faith by meditating in the Word. That commandment was God’s prescription to Joshua to enable him <\/span><span class=\"f_emphasis\">to fight the good fight of faith with success!<\/span><\/p>\n\r"
})
