hmLoadTopic({
hmKeywords:"",
hmTitle:"留言信息",
hmDescription:"标题: Christ the End of the Law 作者: Rev. Paul Cooper 信息摘要: What does it mean that Christ has fulfilled the Law? 经文版权信息 留言目录",
hmPrevLink:"",
hmNextLink:"toc61373213.html",
hmParentLink:"index.html",
hmBreadCrumbs:"",
hmTitlePath:"Message Information",
hmHeader:"<p class=\"p_heading_1_atoc_\"><span class=\"f_heading_1_atoc_\">留言信息<\/span><\/p>\n\r",
hmBody:"<p class=\"p_bullet\"><span class=\"f_bullet\">&nbsp;<\/span><\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 2.1250rem; margin-left: 1.2500rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:2.1250rem;margin-left:-2.1250rem\">&#8226;<\/span><span class=\"f_bullet\" style=\"font-weight: bold;\">标题:<\/span><span class=\"f_bullet\"> Christ the End of the Law<\/span><\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 2.1250rem; margin-left: 1.2500rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:2.1250rem;margin-left:-2.1250rem\">&#8226;<\/span><span class=\"f_bullet\" style=\"font-weight: bold;\">作者:<\/span><span class=\"f_bullet\"> Rev. Paul Cooper<\/span><\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 2.1250rem; margin-left: 1.2500rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:2.1250rem;margin-left:-2.1250rem\">&#8226;<\/span><span class=\"f_bullet\" style=\"font-weight: bold;\">信息摘要: <\/span><span class=\"f_bullet\">What does it mean that Christ has fulfilled the Law?<\/span><\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 2.1250rem; margin-left: 1.2500rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:2.1250rem;margin-left:-2.1250rem\">&#8226;<\/span><span class=\"f_bullet\"><a href=\"https:\/\/messagelink.in\/master_message_directory\/\$_master_directory\/scripture-copyright-info2.html\" target=\"_blank\" class=\"weblink\">经文版权信息<\/a><\/span><\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 2.1250rem; margin-left: 1.2500rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:2.1250rem;margin-left:-2.1250rem\">&#8226;<\/span><span class=\"f_bullet\"><a href=\"https:\/\/messagelink.in\/master_message_directory\/\$_master_directory\/index.html\" target=\"_blank\" class=\"weblink\">留言目录<\/a><\/span><\/p>"
})
