hmLoadTopic({
hmKeywords:"1 Timothy 5:19-21,angels,the Godhead and the mighty angels observe ministry",
hmTitle:"\"I Charge You Before God\"",
hmDescription:"You will note that when Paul is writing Timothy and Titus, he uses the phrase, “I charge you in the presence of God . . . ” For example, consider this verse:",
hmPrevLink:"characteristicsofchristianswithitchingea.html",
hmNextLink:"thehumanelement.html",
hmParentLink:"freedomofconscienceversuslovingthyneighb.html",
hmBreadCrumbs:"<a href=\"introduction.html\">Introduction<\/a> &gt; <a href=\"freedomofconscienceversuslovingthyneighb.html\">Freedom of Conscience versus Loving Thy&nbsp;Neighbor<\/a>",
hmTitlePath:"Introduction > Freedom of Conscience versus Loving Thy Neighbor > I Charge You Before God",
hmHeader:"<p class=\"p_heading_3_atoc_\"><span class=\"f_heading_3_atoc_\">&quot;I Charge You Before God&quot;<\/span><\/p>\n\r",
hmBody:"<p class=\"p_body\"><span class=\"f_body\">You will note that when Paul is writing Timothy and Titus, he uses the phrase, “I charge you in the presence of God . . . ” For example, consider this verse:<\/span><\/p>\n\r<p class=\"p_scripture_head\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture_head\">1 Timothy 5:19-21 English Standard Version (ESV)<\/span><\/p>\n\r<p class=\"p_scripture\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture\">19 Do not admit a charge against an elder except on the evidence of two or three witnesses. 20 As for those who persist in sin, rebuke them in the presence of all so that the rest may stand in fear. 21 In the presence of God and of Christ Jesus and of the elect angels I charge you to keep these rules without prejudging, doing nothing from partiality.<\/span><\/p>\n\r<p class=\"p_body\"><span class=\"f_body\">This is harsh language. Paul reminds his disciples that the Godhead and the mighty angels are carefully observing their pastoral ministry. First, you cannot entertain mere hearsay against an elder. But if there are two or three witnesses, and they persist in sin (meaning they do not repent and refuse to change their ways), they are to be publicly rebuked. Why would Paul charge Timothy to do this in the presence of God, Jesus, and the elect angels?<\/span><\/p>\n\r<p class=\"p_body\"><span class=\"f_body\">Because being an impartial instrument of God’s correction is extremely difficult for any person to do. I have heard that one of the most vital human impulses is to be liked, accepted, and included. One of the quickest ways to be rejected is to call out people’s sins. If you have a word-based preaching or teaching ministry that constantly reproves, rebukes, and corrects<\/span><span class=\"f_body\" style=\"font-family: \'Times New Roman\',Times,Georgia,serif;\">,<\/span><span class=\"f_body\"> you won’t have many people like you. Over time, they could be a temptation to back off from that kind of preaching and make it more palatable. Or to talk about sins that don’t apply to the people in your congregation. If the people in your church are Democrats, they preach against Republicans. If they are Baptists, preach against Presbyterians. Paul is warning Timothy that if you show partiality in his preaching, he will have to deal with God, Jesus, and the elect angels!<\/span><\/p>\n\r<p class=\"p_body\"><span class=\"f_body\">Every pastor has to be reminded that we are working for God and not a<\/span><span class=\"f_body\" style=\"font-family: \'Times New Roman\',Times,Georgia,serif;\"> <\/span><span class=\"f_body\">man!<\/span><\/p>\n\r"
})
