hmLoadTopic({
hmKeywords:"",
hmTitle:"Pray",
hmDescription:"The message is we must pray and how we pray makes all the difference.",
hmPrevLink:"whatgethsemaneteachesusabout%C2%A0prayer.html",
hmNextLink:"watch.html",
hmParentLink:"whatgethsemaneteachesusabout%C2%A0prayer.html",
hmBreadCrumbs:"<a href=\"thechristwho%C2%A0suffered.html\">The Christ Who&nbsp;Suffered<\/a> &gt; <a href=\"whatgethsemaneteachesusabout%C2%A0prayer.html\">What Gethsemane Teaches Us About&nbsp;Prayer<\/a>",
hmTitlePath:"The Christ Who Suffered > What Gethsemane Teaches Us About Prayer > Pray",
hmHeader:"<p class=\"p_heading1\"><span class=\"f_heading1\">Pray<\/span><\/p>\n\r",
hmBody:"<p class=\"p_body\"><span class=\"f_body\">The message is we must pray and how we pray makes all the difference.<\/span><\/p>\n\r<p class=\"p_heading3\"><span class=\"f_heading3\">Reverence<\/span><\/p>\n\r<p class=\"p_scripture_head\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture_head\">Hebrews 5:7 English Standard Version (ESV)<\/span><\/p>\n\r<p class=\"p_scripture\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture\">7 In the days of his flesh, Jesus offered up prayers and supplications, with loud cries and tears, to him who was able to save him from death, and he was heard because of his reverence.<\/span><\/p>\n\r<p class=\"p_body\"><span class=\"f_body\">One reason why our prayers aren’t being answered is that we lack reverence. The Bible says he was heard because of his reverence. Reverence means honor, respect, and deference.<\/span><\/p>\n\r<p class=\"p_body\"><span class=\"f_body\">I fear we have become too casual about prayer. I fear we have become too lazy and careless in our praying. This is disrespectful to our Creator. We must show reverence by being focused, purposeful and having a mindset of reverence.<\/span><\/p>\n\r<p class=\"p_body\"><span class=\"f_body\">When Muslims pray, they are very focused and reverent. They wash. They take off their shoes. They adopt a position of deference. I’m not saying we must do that. But Christians will pray while driving to the grocery store or walking the dog and call that prayer time. They can become too casual, too flip about prayer. They pray to God while thinking about their favorite TV show.<\/span><\/p>\n\r<p class=\"p_heading3\"><span class=\"f_heading3\">Lack of Focus<\/span><\/p>\n\r<p class=\"p_body\"><span class=\"f_body\">Another reason why our prayers are not answered is that we lack focus. Remember, Jesus was face down in the ground, crying loudly to God with tears. We are not praying with the force and intensity of purpose that Jesus demonstrated in the Garden. Of course, I am not saying we must always pray like that. But we must be focused and intense in our praying.<\/span><\/p>\n\r<p class=\"p_body\"><span class=\"f_body\">Jesus gives a clue as to how to reset our prayer life:<\/span><\/p>\n\r<p class=\"p_scripture_head\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture_head\">Luke 5:16 English Standard Version (ESV)<\/span><\/p>\n\r<p class=\"p_scripture\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_scripture\">16 But he would withdraw to desolate places and pray.<\/span><\/p>\n\r<p class=\"p_body\"><span class=\"f_body\">Let’s revisit this idea of getting up and going someplace to pray. Maybe it’s the garage. Maybe it’s the basement. Maybe it’s a lonely, desolate park. But we must go and meet God.<\/span><\/p>\n\r"
})
