hmLoadTopic({
hmKeywords:"",
hmTitle:"Message Information",
hmDescription:"Title: Receiving Wisdom when Suffering Author: Rev. Paul Cooper Message Summary: A look how the Holy Spirit gives the believer wisdom during life\'s trials. Scripture copyright",
hmPrevLink:"",
hmNextLink:"wisdomduringsuffering.html",
hmParentLink:"index.html",
hmBreadCrumbs:"",
hmTitlePath:"Message Information",
hmHeader:"<p class=\"p_heading_1_atoc_\"><span class=\"f_heading_1_atoc_\">Message Information<\/span><\/p>\n\r",
hmBody:"<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 1.5000rem; margin-left: 2.0000rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">&#8226;<\/span><span class=\"f_bullet\" style=\"font-weight: bold;\">Title:<\/span><span class=\"f_bullet\"> Receiving Wisdom when Suffering<\/span><\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 1.5000rem; margin-left: 2.0000rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">&#8226;<\/span><span class=\"f_bullet\" style=\"font-weight: bold;\">Author:<\/span><span class=\"f_bullet\"> Rev. Paul Cooper<\/span><\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 1.5000rem; margin-left: 2.0000rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">&#8226;<\/span><span class=\"f_bullet\" style=\"font-weight: bold;\">Message Summary: <\/span><span class=\"f_bullet\">A look how the Holy Spirit gives the believer wisdom during life\'s trials.<\/span><\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 1.5000rem; margin-left: 2.0000rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">&#8226;<\/span><span class=\"f_bullet\"><a href=\"https:\/\/messagelink.in\/master_message_directory\/\$_master_directory\/scripture-copyright-info2.html\" target=\"_blank\" class=\"weblink\">Scripture copyright information<\/a><\/span><\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 1.5000rem; margin-left: 2.0000rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">&#8226;<\/span><span class=\"f_bullet\"><a href=\"https:\/\/messagelink.in\/master_message_directory\/\$_master_directory\/index.html\" target=\"_blank\" class=\"weblink\">Message Directory<\/a><\/span><\/p>"
})
