hmLoadTopic({
hmKeywords:"",
hmTitle:"Conclusion",
hmDescription:"My word to you is once God gives you a quickened word about what to do, be relentless in your pursuit of what God said. Don’t stop until you have recovered everything the devil...",
hmPrevLink:"theholyspiritleadsinatimeof%C2%A0trouble_.html",
hmNextLink:"",
hmParentLink:"wisdomduringsuffering.html",
hmBreadCrumbs:"<a href=\"wisdomduringsuffering.html\">Receiving Wisdom when Suffering<\/a>",
hmTitlePath:"Receiving Wisdom when Suffering > Conclusion",
hmHeader:"<p class=\"p_heading_2_atoc_\"><span class=\"f_heading_2_atoc_\">Conclusion<\/span><\/p>\n\r",
hmBody:"<p class=\"p_body\"><span class=\"f_body\">My word to you is once God gives you a quickened word about what to do, be relentless in your pursuit of what God said. Don’t stop until you have recovered everything the devil stole from<\/span><span class=\"f_body\" style=\"font-family: \'Times New Roman\',Times,Georgia,serif;\"> <\/span><span class=\"f_body\">you!<\/span><\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 1.5000rem; margin-left: 2.0000rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">&#8226;<\/span><span class=\"f_bullet\">Don’t stop<\/span><span class=\"f_bullet\" style=\"font-family: \'Times New Roman\',Times,Georgia,serif;\"> <\/span><span class=\"f_bullet\">praying.<\/span><\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 1.5000rem; margin-left: 2.0000rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">&#8226;<\/span><span class=\"f_bullet\">Don’t stop<\/span><span class=\"f_bullet\" style=\"font-family: \'Times New Roman\',Times,Georgia,serif;\"> <\/span><span class=\"f_bullet\">giving.<\/span><\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 1.5000rem; margin-left: 2.0000rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">&#8226;<\/span><span class=\"f_bullet\">Don’t stop speaking God’s<\/span><span class=\"f_bullet\" style=\"font-family: \'Times New Roman\',Times,Georgia,serif;\"> <\/span><span class=\"f_bullet\">word.<\/span><\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 1.5000rem; margin-left: 2.0000rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">&#8226;<\/span><span class=\"f_bullet\">Don’t stop coming to church and fellowshipping with the<\/span><span class=\"f_bullet\" style=\"font-family: \'Times New Roman\',Times,Georgia,serif;\"> <\/span><span class=\"f_bullet\">saints.<\/span><\/p>\n\r<p class=\"p_bullet\" style=\"text-indent: 0; padding-left: 1.5000rem; margin-left: 2.0000rem;\"><span class=\"f_bullet\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">&#8226;<\/span><span class=\"f_bullet\">Don’t stop until you have the<\/span><span class=\"f_bullet\" style=\"font-family: \'Times New Roman\',Times,Georgia,serif;\"> <\/span><span class=\"f_bullet\">victory.<\/span><\/p>\n\r<p class=\"p_body\"><span class=\"f_close\">In the name of God, Amen.<\/span><\/p>\n\r"
})
